[connections.gsheets_postcodes]
spreadsheet = 'https://docs.google.com/spreadsheets/d/1fJ-SJPjldp8-LuaT9wdp_FoS518gSNlkN5wN849EUlo/edit?usp=sharing'

[connections.gsheets_wards]
spreadsheet = 'https://docs.google.com/spreadsheets/d/1tmk5cTIc3TNScbSeJgVMKcsCieVLtiY8YjS1Ma3rRLo/edit?usp=sharing'
